package com.redspark.nycl.domain;

public enum FixtureRule {
  ONLY_PLAY_HOME_GAMES_ON_PREFERRED_DAY,
  ONLY_PLAY_ONCE_A_WEEK,
  NO_CONTIGUOUS_FIXTURES,
  ONLY_PLAY_IF_CLUB_HAS_HOME_CAPACITY,
  NO_CONTIGUOUS_AGE_GROUP_FIXTURES,
}
