package com.redspark.nycl.domain;

public enum NYCL_CLUB {
  ATTENBOROUGH,
  BRAMCOTE,
  CALVERTON,
  CARRINGTON,
  WI_CAVALIERS,
  CAYTHORPE,
  EASTWOOD,
  ELLERSLIE,
  GEDLING_COLLIERY,
  GEDLING_AND_SHERWOOD,
  GOTHAM,
  ICCA,
  KIMBERLEY,
  KIRBY_PORTLAND,
  NOTTS_AND_ARNOLD,
  PLUMTREE,
  RADCLIFFE_ON_TRENT,
  RUDDINGTON,
  WEST_BRIDGFORDIANS,
  WOLLATON
}
